export const ADD_CITY = 'ADD_CITY';

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAULURE = 'FETCHING_DATA_FAULURE';
